In [35]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
from sklearn import metrics
%matplotlib inline

In [15]:
digits = load_digits()

In [46]:
X, y = load_digits(return_X_y=True)
print(len(X))
X_train, X_test, y_train, y_test = train_test_split(X,
                                                    y,
                                                    test_size=0.1)

1797


In [47]:
neigh_10 = KNeighborsClassifier(n_neighbors = 10, weights = 'distance')
neigh_10_train = neigh_10.fit(X_train, y_train)

In [48]:
y_pred = neigh_10.predict(X_test)

In [49]:
# Accuracy
print(metrics.accuracy_score(y_test, y_pred))

1.0


In [50]:
# Classification report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        17
           1       1.00      1.00      1.00        19
           2       1.00      1.00      1.00        25
           3       1.00      1.00      1.00        21
           4       1.00      1.00      1.00        15
           5       1.00      1.00      1.00        24
           6       1.00      1.00      1.00        12
           7       1.00      1.00      1.00        15
           8       1.00      1.00      1.00        15
           9       1.00      1.00      1.00        17

    accuracy                           1.00       180
   macro avg       1.00      1.00      1.00       180
weighted avg       1.00      1.00      1.00       180



In [51]:
# Confusion Matrix
print(confusion_matrix(y_test, y_pred))

[[17  0  0  0  0  0  0  0  0  0]
 [ 0 19  0  0  0  0  0  0  0  0]
 [ 0  0 25  0  0  0  0  0  0  0]
 [ 0  0  0 21  0  0  0  0  0  0]
 [ 0  0  0  0 15  0  0  0  0  0]
 [ 0  0  0  0  0 24  0  0  0  0]
 [ 0  0  0  0  0  0 12  0  0  0]
 [ 0  0  0  0  0  0  0 15  0  0]
 [ 0  0  0  0  0  0  0  0 15  0]
 [ 0  0  0  0  0  0  0  0  0 17]]


In [52]:
# test_size를 0.33 으로 설정하였을 경우


X, y = load_digits(return_X_y=True)
print(len(X))
X_train, X_test, y_train, y_test = train_test_split(X,
                                                    y,
                                                    test_size=0.33)
neigh_10 = KNeighborsClassifier(n_neighbors = 10, weights = 'distance')
neigh_10_train = neigh_10.fit(X_train, y_train)
y_pred = neigh_10.predict(X_test)

1797


In [53]:
# Accuracy
print(metrics.accuracy_score(y_test, y_pred))

0.9848484848484849


In [54]:
# Classification report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        57
           1       0.97      1.00      0.99        66
           2       1.00      0.98      0.99        58
           3       1.00      1.00      1.00        67
           4       1.00      1.00      1.00        54
           5       0.98      0.93      0.96        59
           6       0.98      1.00      0.99        48
           7       0.98      1.00      0.99        60
           8       0.98      0.97      0.98        62
           9       0.95      0.97      0.96        63

    accuracy                           0.98       594
   macro avg       0.99      0.99      0.99       594
weighted avg       0.98      0.98      0.98       594



In [55]:
# Confusion Matrix
print(confusion_matrix(y_test, y_pred))

[[57  0  0  0  0  0  0  0  0  0]
 [ 0 66  0  0  0  0  0  0  0  0]
 [ 0  0 57  0  0  0  0  1  0  0]
 [ 0  0  0 67  0  0  0  0  0  0]
 [ 0  0  0  0 54  0  0  0  0  0]
 [ 0  0  0  0  0 55  1  0  0  3]
 [ 0  0  0  0  0  0 48  0  0  0]
 [ 0  0  0  0  0  0  0 60  0  0]
 [ 0  2  0  0  0  0  0  0 60  0]
 [ 0  0  0  0  0  1  0  0  1 61]]


강사님 해설

In [57]:
d = load_digits()

In [58]:
d

{'DESCR': ".. _digits_dataset:\n\nOptical recognition of handwritten digits dataset\n--------------------------------------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 5620\n    :Number of Attributes: 64\n    :Attribute Information: 8x8 image of integer pixels in the range 0..16.\n    :Missing Attribute Values: None\n    :Creator: E. Alpaydin (alpaydin '@' boun.edu.tr)\n    :Date: July; 1998\n\nThis is a copy of the test set of the UCI ML hand-written digits datasets\nhttps://archive.ics.uci.edu/ml/datasets/Optical+Recognition+of+Handwritten+Digits\n\nThe data set contains images of hand-written digits: 10 classes where\neach class refers to a digit.\n\nPreprocessing programs made available by NIST were used to extract\nnormalized bitmaps of handwritten digits from a preprinted form. From a\ntotal of 43 people, 30 contributed to the training set and different 13\nto the test set. 32x32 bitmaps are divided into nonoverlapping blocks of\n4x4 and the number o

In [59]:
# target이 label! 1797개의 이미지 8by8

d.images.shape

(1797, 8, 8)

In [60]:
# train_test 위해 split

(trainData, testData, trainLabels, testLabels) = train_test_split(np.array(d.data), d.target, test_size=0.25, random_state=42)

In [61]:
trainData.shape

(1347, 64)

In [63]:
model = KNeighborsClassifier(10)
model.fit(trainData, trainLabels)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=10, p=2,
                     weights='uniform')

In [64]:
yhat = model.predict(testData)

In [65]:
confusion_matrix(yhat, testLabels)

array([[43,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0, 37,  0,  0,  0,  0,  0,  0,  2,  0],
       [ 0,  0, 38,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0, 46,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 55,  0,  0,  0,  0,  1],
       [ 0,  0,  0,  0,  0, 57,  0,  0,  0,  1],
       [ 0,  0,  0,  0,  0,  1, 45,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0, 41,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0, 36,  0],
       [ 0,  0,  0,  0,  0,  1,  0,  0,  0, 46]])